### PR TITLE
fix wrong so name for posix platforms

### PR DESCRIPTION
**Pull request by BBasile**

### CODE REVIEW

**Comment by mdparker** [comment]
Sorry, I missed this. Thanks!

**Comment by mdparker** [comment]
I'll tag a release for DUB shortly.

**Comment by mdparker** [comment]
This is now available in version 1.3.1 and 2.0.0-alpha.2. I also added a similar fix for Lua 5.2 in 1.2.4.

**Comment by BBasile** [comment]
thanks.

**Pull request merged**
